artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  # source_URL: https://github.com/abhishek-jana/Datasets/raw/main/NSL-KDD.zip
  source_URL: https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/72ptz43s9v-1.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data.csv
  preprocessed_data: artifacts/data_validation/preprocessed_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_validation/preprocessed_data.csv
  transformer_path: artifacts/data_transformation/transformer.pkl


model_trainer:
  root_dir: artifacts/model_trainer
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  # x_train_path: artifacts/data_transformation/test.csv
  # x_test_path: artifacts/data_transformation/test.csv
  # y_train_path: artifacts/data_transformation/test.csv
  # y_test_path: artifacts/data_transformation/test.csv
  transformer_path: artifacts/data_transformation/transformer.pkl
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json